name: travel_hour
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.0.0+8

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  
  apple_sign_in: ^0.1.0
  animated_bottom_navigation_bar: ^0.1.2+2
  cached_network_image: ^2.3.3
  carousel_pro: ^1.0.0
  cloud_firestore: ^0.14.1+3
  connectivity: ^0.4.9+5
  cupertino_icons: ^1.0.0
  dots_indicator: ^1.0.0
  easy_localization: ^2.3.3
  # facebook_audience_network: ^0.7.1
  firebase_analytics: ^6.0.2
  firebase_admob: ^0.10.0+2
  firebase_auth: ^0.18.1+2
  firebase_core: ^0.5.0+1
  firebase_messaging: ^7.0.3
  firebase_storage: ^4.0.1
  firebase_in_app_messaging: ^0.2.0+3
  flare_flutter: ^1.6.2
  flutter_facebook_login: ^3.0.0
  flutter_html: ^0.11.1
  flutter_icons: ^1.1.0
  flutter_staggered_animations: ^0.1.2
  flutter_widget_from_html: ^0.5.1+3
  flutter_polyline_points: ^0.2.4
  geo: ^0.2.4
  google_fonts: ^1.1.1
  google_maps_flutter: ^1.0.3
  google_sign_in: ^4.5.5
  html: ^0.14.0+4
  html_unescape: ^1.0.1+3
  http: ^0.12.2
  image_picker: ^0.6.7+12
  intl: ^0.16.0
  launch_review: ^2.0.0
  line_icons: ^0.2.0
  md2_tab_indicator: ^1.0.2
  package_info: ^0.4.0+16
  provider: ^4.3.2+2
  share: ^0.6.5+3
  shared_preferences: ^0.5.12+2
  skeleton_text: ^1.0.0
  sliding_up_panel: ^0.3.5
  toast: ^0.1.5
  url_launcher: ^5.7.5




  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"






flutter:

  uses-material-design: true






  assets:
    - assets/images/search.png
    - assets/images/travel1.png
    - assets/images/travel2.png
    - assets/flr/success.flr
    - assets/images/travel4.png
    - assets/images/travel5.png
    - assets/images/travel6.png
    - assets/images/empty.png
    - assets/images/restaurant.png
    - assets/images/hotel.png
    - assets/images/splash.png
    - assets/images/icon.png
    - assets/images/hotel_pin.png
    - assets/images/restaurant_pin.png
    - assets/images/destination_map_marker.png
    - assets/images/driving_pin.png
    - assets/translations/

  fonts:

    - family: Muli
      fonts:
        # - asset: fonts/Montserrat-Light.ttf
        #   weight: 400
        - asset: fonts/Muli-Regular.ttf
          weight: 500
        - asset: fonts/Muli-Medium.ttf
          weight: 600
        - asset: fonts/Muli-SemiBold.ttf
          weight: 700
        - asset: fonts/Muli-Bold.ttf
          weight: 800
